Salik School Management System/Areas/Admin/Controllers/StageController.cs
using Microsoft.AspNetCore.Mvc;
using SchoolManagement.DataAccess.Repository.IRepository;
using SchoolManagement.Models;

namespace Salik_School_Management_System.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class StageController : Controller
    {

        private readonly IUnitOfWork _unitOfWork;

        public StageController(IUnitOfWork unitOfWork)
        {
            this._unitOfWork = unitOfWork;
        }

        public async Task<IActionResult> Index()
        {
            var response =_unitOfWork.stage.GetAllFully();
            var responseTask = await response;
            IEnumerable<Stage> stages = (IEnumerable<Stage>)responseTask;
            return View(stages);
        }

        public async Task<IActionResult> AllStudents(int stNum)
        {

            if (stNum == 0)
            {
                return NotFound();
            }
            var response = _unitOfWork.stage.GetByStageNumber(k=>k.StageNumber==stNum);
            var responseTask = await response;
            Stage Stage = responseTask;
            if (Stage == null)
            {
                return NotFound();
            }
            return View(Stage);
        }
        public async Task<IActionResult> AllTopics(int stNum)
        {

            if (stNum == 0)
            {
                return NotFound();
            }
            var response = _unitOfWork.stage.GetByStageNumber(k => k.StageNumber == stNum);
            var responsetask = await response;
            Stage Stage = responsetask;

            if (Stage == null)
            {
                return NotFound();
            }
            return View(Stage);
        }
    }
}

Salik School Management System/Areas/Admin/Controllers/StudentController.cs
using Microsoft.AspNetCore.Mvc;
using SchoolManagement.DataAccess.Repository.IRepository;
using SchoolManagement.Models;

namespace Salik_School_Management_System.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class StudentController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public StudentController(IUnitOfWork unitOfWork)
        {
            this._unitOfWork = unitOfWork;
        }
        public async Task<IActionResult> Index()
        {

            //IEnumerable<Student> listOfAllStudents

            var response = _unitOfWork.student.GetAllFully();
            var responseTask = await response;

            IEnumerable<Student> listOfAllStudents = (IEnumerable<Student>)responseTask;



            return View(listOfAllStudents);
        }
        public IActionResult Create()
        {
          
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Student std,int stNum)
        {

            if(stNum > 6 || stNum < 1)
            {
                return new NotFoundResult();
            }

            var response = _unitOfWork.stage.GetByStageNumber(k => k.StageNumber == stNum);
            Stage stage = await response;
            

            if (ModelState.IsValid)
            {
                StudentTopic st0 = new StudentTopic()
                {
                    student = std,
                    topic = stage.topicList.ElementAt(0)

                };

                StudentTopic st1 = new StudentTopic()
                {
                    student = std,
                    topic = stage.topicList.ElementAt(1)

                };

                StudentTopic st2 = new StudentTopic()
                {
                    student = std,
                    topic = stage.topicList.ElementAt(2)

                }; 
                StudentTopic st3 = new StudentTopic()
                {
                    student = std,
                    topic = stage.topicList.ElementAt(3)

                };


                List<StudentTopic> ls = new List<StudentTopic>();
                ls.AddRange(new List<StudentTopic>() { st0,st1,st2,st3});
                //        Console.WriteLine(ls.ElementAt(0).topic.Name);
                std.topics = ls;
                std.stage = stage;
                _unitOfWork.student.Add(std);
              await  _unitOfWork.Save();
                TempData["success"] = "Category created successfully";
                return RedirectToAction("Index");
            }
            return View(std);
        }
        [HttpGet]
       public async Task<IActionResult> Edit(int Id)
        {


            if (Id == 0)
            {
                return NotFound();

            }
            var response = _unitOfWork.student.GetFully(Id);
            Student student = await response;
            if (student == null)
            {
                return NotFound();
            }
            return View(student);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Student student, int stNum)
        {


            if (ModelState.IsValid)
            {

                if (stNum > 6 || stNum < 1)
                {
                    return new NotFoundResult();
                }
                //.Where(k => k.StudentId == student.Id).ToList()

                //student.topics = _unitOfWork.studenTopic.GetAll().Result.Where(k => k.StudentId == student.Id).ToList();

                var response = _unitOfWork.studenTopic.GetAll();
                var responsetask = await response;
                student.topics = responsetask.Where(k => k.StudentId == student.Id).ToList();

                if (student?.stage?.StageNumber != stNum)
                {


                   
                    _unitOfWork.studenTopic.RemoveRange(student.topics);
                    student.stage=null;

                     

                    _unitOfWork.student.UpdateEntity(student);
                    await _unitOfWork.Save();

                    //before
                    //Stage stage = _unitOfWork.stage.GetFirstOrDefault(l=>l.StageNumber== stNum).Result;
                    //correct wait to get the result way by async
                    var response1 = _unitOfWork.stage.GetFirstOrDefault(l => l.StageNumber == stNum);
                    var responsest=await response1;
                    Stage stage =  responsest;


                    //stage.topicList = _unitOfWork.topic.GetAll().Result.Where(k => k.StageId == stage.Id).ToList();

                    var topresponse = _unitOfWork.topic.GetAll();
                    var responsetopawait = await topresponse;
                    stage.topicList=responsetopawait.Where(k => k.StageId == stage.Id).ToList();


                    //stage.students = _unitOfWork.student.GetAll().Result.Where(k => k.StageId == stage.Id).ToList();

                    var stdResponse = _unitOfWork.student.GetAll();
                    var stdresponseResult = await stdResponse;
                    stage.students= stdresponseResult.Where(k => k.StageId == stage.Id).ToList();

                    stage.students.Add(student);
                    student.stage = stage;
                    StudentTopic st0 = new StudentTopic()
                    {
                        student = student,
                        topic = stage.topicList.ElementAt(0)

                    };

                    StudentTopic st1 = new StudentTopic()
                    {
                        student = student,
                        topic = stage.topicList.ElementAt(1)

                    };

                    StudentTopic st2 = new StudentTopic()
                    {
                        student = student,
                        topic = stage.topicList.ElementAt(2)

                    };
                    StudentTopic st3 = new StudentTopic()
                    {
                        student = student,
                        topic = stage.topicList.ElementAt(3)

                    };

                    
                    List<StudentTopic> ls = new();
                    ls.AddRange(new List<StudentTopic>() { st0, st1, st2, st3 });
                    // _unitOfWork.studenTopic.RemoveRange(student.topics);
                    
                    student.topics.AddRange(ls);

                }



                _unitOfWork.student.UpdateEntity(student);
               await _unitOfWork.Save();
                TempData["success"] = "Student information edited successfully";
                return RedirectToAction("Index");
            }
            return View(student);
        }

        public async Task<IActionResult> Delete(int Id)
        {
            

            if (Id == 0)
            {
                return NotFound();

            }

            var response = _unitOfWork.student.GetFully(Id);
            var responseResult = await response;
            Student student = responseResult;
            if (student == null)
            {
                return NotFound();
            }
            return View(student);
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(Student std)
        {

            if (std == null)
            {
                return NotFound();
            }

            _unitOfWork.student.Remove(std);
           await _unitOfWork.Save();
            TempData["success"] = "student deleted successfully";
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> AllTopics(int Id)
        {
            

            if (Id == 0)
            {
                return NotFound();

            }

            //var student = _unitOfWork.student.GetFully(Id).Result;

            var response1 = _unitOfWork.student.GetFully(Id);
            var responseResult = await response1;
            Student student = responseResult;


            student.stage =  _unitOfWork.stage.GetFully(student.StageId).Result;

            var response2 = _unitOfWork.stage.GetFully(student.StageId);
            var response2result= await response2;
            student.stage = response2result;
            return View(student);
             
        }



    }
}

Salik School Management System/Areas/Admin/Controllers/TopicsController.cs
using Microsoft.AspNetCore.Mvc;
using SchoolManagement.DataAccess.Repository.IRepository;
using SchoolManagement.Models;


namespace Salik_School_Management_System.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class TopicsController : Controller
    {


        private readonly IUnitOfWork _unitOfWork;

        public TopicsController(IUnitOfWork unitOfWork)
        {
            this._unitOfWork = unitOfWork;
        }
        public async Task<IActionResult> IndexAsync()
        {

            //IEnumerable<Topic> topicList = (IEnumerable<Topic>)_unitOfWork.topic.GetAllFully().Result;

            var response = _unitOfWork.topic.GetAllFully();
            var responseresult = await response;
            IEnumerable<Topic> topicList = (IEnumerable<Topic>)responseresult;
            return View(topicList);
        }

        public async Task<IActionResult> EditAsync(int Id)
        {
            if(Id == 0)
            {
                return NotFound();
            }
            //Topic topicToEdit = _unitOfWork.topic.GetFully(Id).Result;

            var response = _unitOfWork.topic.GetFully(Id);
            var responseResult = await response;
            Topic topicToEdit = responseResult;

            if (topicToEdit == null)
            {
                return NotFound(Id);
            }
            return View(topicToEdit);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Topic topic)
        {
            if(topic == null)
            {
                return NotFound();
            }
            _unitOfWork.topic.UpdateEntity(topic);
            await  _unitOfWork.Save();
            TempData["success"] = "Topic details edited successfully";
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> AllStudentsAsync(int Id)
        {
            //Topic topic = _unitOfWork.topic.GetFully(Id).Result;
            var response = _unitOfWork.topic.GetFully(Id);
            var responseResult = await response;
            Topic topic = responseResult;


            //topic.Stage=_unitOfWork.stage.GetFully(topic.StageId).Result;
            var response2 = _unitOfWork.stage.GetFully(topic.StageId);
            var responseResult2 = await response2;
            topic.Stage = responseResult2;
            return View(topic);
        }
        [HttpGet]
        public async Task<IActionResult> AssignTeacherAsync(int Id)
        {
            //Topic topic = _unitOfWork.topic.GetFully(Id).Result;
            var response = _unitOfWork.topic.GetFully(Id);
            var responseResult = await response;
            Topic topic = responseResult;
            //IEnumerable<Teacher> teachers = (IEnumerable<Teacher>)_unitOfWork.teacher.GetAllFully().Result;

            var response2 = _unitOfWork.teacher.GetAllFully();
            var responseresult2 = await response2;
            IEnumerable<SchoolManagement.Models.Teacher> teachers = (IEnumerable<SchoolManagement.Models.Teacher>)responseresult2;
            TempData.Add("Id", Id);
            return View(teachers);
        }

        //to be tested 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AssignTeacher( int Id, int TopicId)
        {
            var response = _unitOfWork.topic.GetFully(TopicId);
            var responseResult = await response;
            Topic topic = responseResult;
            // Topic topic = _unitOfWork.topic.GetFully(TopicId).Result;

            var response2 = _unitOfWork.teacher.GetFully(Id);
            var responseResult2 = await response2;
            SchoolManagement.Models.Teacher teacher = responseResult2;
          //  Teacher teacher = _unitOfWork.teacher.GetFully(Id).Result;
            topic.teacher = teacher;
            teacher?.topics?.Add(topic);

            if (teacher.topics.Contains(topic))
            {
                teacher.topics.Remove(topic);
            }

            await _unitOfWork.Save();
            TempData["success"] = "teacher was assigned successfully";
            return RedirectToAction("Index");
            
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> RemoveTeacher(int Id, int TopicId)
        {
            var response = _unitOfWork.topic.GetFully(Id);
            var responseResult = await response;
            Topic topic = responseResult;
            //Topic topic = _unitOfWork.topic.GetFully(TopicId).Result;
            var response2 = _unitOfWork.teacher.GetFully(Id);
            var responseResult2 = await response2;
            SchoolManagement.Models.Teacher teacher = responseResult2;
           // Teacher teacher = _unitOfWork.teacher.GetFully(Id).Result;
            topic.teacher =null;
            

            if (teacher.topics.Contains(topic))
            {
                teacher.topics.Remove(topic);
            }

            await _unitOfWork.Save();
            TempData["success"] = "teacher was Removed successfully";
            return RedirectToAction("Index");

        }
    }
}

Salik School Management System/Areas/Teacher/Controllers/TeachersController.cs
using Microsoft.AspNetCore.Mvc;
using SchoolManagement.DataAccess.Repository.IRepository;
using SchoolManagement.Models;

namespace Salik_School_Management_System.Areas.Teacher.Controllers
{
    [Area("Teacher")]
    public class TeachersController : Controller
    {

        private readonly IUnitOfWork _unitOfWork;

        public TeachersController(IUnitOfWork unitOfWork)
        {
            this._unitOfWork = unitOfWork;
        }

        public async Task<IActionResult> IndexAsync()
        {
            var result = await _unitOfWork.teacher.GetAll();
            var teachers = result;

            return View(teachers);
        }


        public async Task<IActionResult> AllTopics(int Id)
        {


            if (Id == 0)
            {
                return NotFound();

            }

            //var student = _unitOfWork.student.GetFully(Id).Result;

            var response1 = _unitOfWork.teacher.GetFully(Id);
            var responseResult = await response1;
            SchoolManagement.Models.Teacher teacher = responseResult;

            var response2 = _unitOfWork.topic.GetAllFullyByTeacherId(teacher.Id);
            var result =  await response2;
            teacher.topics = result;

            return View(teacher);

        }

        public async Task<IActionResult> StudentTopic(int Id)
        {
            if (Id == 0) return NotFound();

            var response=(IEnumerable<SchoolManagement.Models.StudentTopic>)_unitOfWork.studenTopic.GetAllWitStudentById(Id);
           
          foreach (var topic in response)
            {
                topic.TopicId = Id;
            }
            

            return View(response);
        }
        [HttpPost]
        public async Task<IActionResult> UpdateGrade(StudentTopic stdt,int grade)
        {
            if (stdt == null) return NotFound();
            stdt.grade = grade;
             if(stdt.grade > 50)
            {
                stdt.isPassedTopic = true;
            }
            else { stdt.isPassedTopic = false; }

             _unitOfWork.studenTopic.UpdateEntity(stdt);
            await _unitOfWork.Save();

            int v = (int)stdt.TopicId;
            return RedirectToAction("StudentTopic", new {Id= v });
        }

    }
}

Salik School Management System/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Salik_School_Management_System</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/bootswatchTheme.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Salik_School_Management_System.styles.css" asp-append-version="true" />      
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css">
</head>
<body>





   @* <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Salik_School_Management_System</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>*@


    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarColor01">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
         <a class="nav-link" asp-area="Admin" asp-controller="Home" asp-action="Index">Home</a>
        </li>
        <li class="nav-item">
         <a class="nav-link" asp-area="Admin" asp-controller="Student" asp-action="Index">Student</a>
        </li>
        <li class="nav-item">
         <a class="nav-link" asp-area="Admin" asp-controller="Stage" asp-action="Index">Stage</a>
        </li>
        <li class="nav-item">
         <a class="nav-link" asp-area="Admin" asp-controller="Teacher" asp-action="Index">Teacher</a>
        </li>
         <li class="nav-item">
         <a class="nav-link" asp-area="Admin" asp-controller="Topics" asp-action="Index" >Topics</a>
        </li>
        <li class="nav-item">
         <a class="nav-link" asp-area="Teacher" asp-controller="Teachers" asp-action="Index">Teacher page</a>
        </li>
        @*<li class="nav-item dropdown" >
          <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Dropdown</a>
          <div class="dropdown-menu" >
         <a class="dropdown-item" asp-area="Admin" asp-controller="Student" asp-action="Index">Student</a>
         <a class="dropdown-item" asp-area="Admin" asp-controller="Stage" asp-action="Index">Stage</a>
         <a class="dropdown-item" asp-area="Admin" asp-controller="Teacher" asp-action="Index">Teacher</a>
         <a class="dropdown-item" asp-area="Admin" asp-controller="Topics" asp-action="Index">Topics</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Separated link</a>
          </div>
        </li>*@
      </ul> 

      <img src="/css/images/Logo.png" width="5%" height="4%" style="margin-right:35%; " />

     <form class="d-flex">
        <input class="form-control me-sm-2" type="text" placeholder="Search">
        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>





    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>









    <footer class="page-footer font-small purple pt-2 bg-primary fixed-bottom" >
        <div class="container" style="text-align:center">
            &copy; 2022 - Salik School Management System
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Salik School Management System/Views/Shared/_Notification.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@if(TempData["success"]!=null)
{
	<script src="~/lib/jquery/dist/jquery.min.js"></script>

	<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
	<script type="text/javascript">toastr.success('@TempData["success"]') </script>
}

@if(TempData["error"]!=null)
{

		<script src="~/lib/jquery/dist/jquery.min.js"></script>

	<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
	<h2>@TempData["error"]</h2>

	<script type="text/javascript">toastr.error('@TempData["error"]') </script>
}